server:
  port: 8585
  servlet:
    context-path: /controlerelatorio
  api_name: /api/v2

application:
  description: Projeto para realizar o controle e geração de relatorios
  version: 0.0.1

spring:
  cache:
    type: redis
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.2.106:5432/ControleRelatorio
    username: postgres
    password: root
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
  redis:
    url: redis://192.168.2.106
    host: 192.168.2.106
    port: 6379
    expiretime: 60
  boot:
    admin:
      client:
        url: http://localhost:8585/controlerelatorio

management:
  security:
    enabled: false

jwt:
  secret: usersecretforjwtauthenticateoratoroeuaroupadoreideromalalalameudeuscomoessabencaodechave
  valid: 60 #Define em Minutos o tempo valido do Token

info:
  app:
    developer: SawCunha
  java:
    source: 11
    target: 11

access_denied:
  reason: Você não possui permissão suficiente, favor contactar o administrador do sistema.
  message: Acesso negado